select 
    "twitter" as platform,
    `date`, 
    0 as add_to_cart, 
    clicks, 
    comments, 
    engagements, 
    impressions, 
    0 as installs, 
    likes, 
    url_clicks as link_clicks, 
    0 as post_click_conversions,
    0 as post_view_conversions,
    0 as posts,
    0 as purchase,
    0 as registrations,
    0 as revenue,
    0 as shares,
    spend,
    0 as total_conversions,
    video_total_views as video_views,
    cast(null as string) as ad_id,
    cast(null as string) as adset_id,
    cast(campaign_id as string) as campaign_id,
    channel,
    cast(null as string) as creative_id,
    cast(null as string) as placement_id

from {{ ref('src_promoted_tweets_twitter_all_data') }}